name: state_beacon_core
description: A reactive primitive and simple state managerment solution for dart.
version: 0.39.1
repository: https://github.com/jinyus/dart_beacon

environment:
    sdk: ^3.0.0

dev_dependencies:
    test: ^1.24.0
    very_good_analysis: ^5.1.0

platforms:
    android:
    ios:
    linux:
    macos:
    web:
    windows:

topics:
    - state
    - signal
    - reactive
    - beacon
