name: state_beacon
description: A reactive primitive for dart and flutter
version: 0.1.0
repository: https://github.com/jinyus/dart_beacon

environment:
    sdk: ^3.1.5

dev_dependencies:
    lints: ^3.0.0
    test: ^1.21.0
