name: state_beacon
description: A reactive primitive for dart and flutter
version: 0.13.4
repository: https://github.com/jinyus/dart_beacon

environment:
    sdk: ^3.1.5
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_lints: ^3.0.0
    flutter_test:
        sdk: flutter
    lints: ^3.0.0

platforms:
    android:
    ios:
    linux:
    macos:
    web:
    windows:

topics:
    - state
    - signal
    - reactive
    - beacon
