name: custom_lint_example_app
publish_to: none

environment:
    sdk: ">=2.16.0 <4.0.0"

dependencies:
    state_beacon: ^0.34.0

dev_dependencies:
    custom_lint:
    state_beacon_lint:
        path: ../../state_beacon_lints
